version: 2.1

parameters:
  slack-mentions:
    type: string
    default: 'S01JP5A3ACQ'

orbs:
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.1.0

executors:
  terraform:
    docker:
      - image: techallylw/terraform:latest
  alpine:
    docker:
      - image: cibuilds/base:latest
    resource_class: small

jobs:
  terraform-test:
    executor: terraform
    steps:
      - checkout
      - run: scripts/ci_tests.sh
  verify-release:
    executor: alpine
    steps:
      - checkout
      - run: scripts/release.sh verify
  trigger-release:
    executor: alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d2:f4:31:07:9c:f4:07:8c:20:c2:a1:1a:0e:c8:6a:42"
      - run: scripts/release.sh trigger
  release:
    executor: alpine
    steps:
      - checkout
      - jq/install
      - slack/notify:
          mentions: << pipeline.parameters.slack-mentions >>
          message: Releasing a new version of the terraform-provisioning repository
      - run: scripts/release.sh publish
      - slack/status:
          fail_only: false
          mentions: << pipeline.parameters.slack-mentions >>

workflows:
  version: 2
  build_test_trigger-release:
    jobs:
      - terraform-test
      - trigger-release:
          requires:
            - terraform-test
          filters:
            branches:
              only: master

  verify-release:
    jobs:
      - verify-release:
          filters:
             branches:
               only: release

  release-from-tag:
    jobs:
      - release:
          filters:
            tags:
               only: /^v.*/
            branches:
              ignore: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only: master
    jobs:
      - terraform-test
